Add MIG_mose CI Action (#243)
* ➕Add migmose as dependency

* 👷‍♂️Add CI Action to automatically run migmose

* add token

* fix copy paste

* fix copy paste 2

* eemp

* file minus type

* fix path

Error: Invalid value for '-eemp' / '--edi-energy-mirror-path': Directory 'edi_energy_mirror/FV2104' does not exist.

* Update migmose.yml

* changed cli command for migmose

* added missing path to cli command for migmose

* removed FV 2104 and FV2110 as they do not provide .docx files

* added comment for token scope

---------

Co-authored-by: DeltaDaniel <139119540+DeltaDaniel@users.noreply.github.com>